### ISSUE TITLE
9月1日晋江再次更新了字体，请大佬指点一下在线阅读脚本的问题，万分感谢！

### ISSUE THREAD

**Issue by wumigg** [yingziwu/jjwxcFontTables#1]
首先，特别感谢大佬为解决晋江这个字体问题做出的努力！这里还是有问题向您请教一下，希望您不要嫌弃orz。

作为完全不懂代码的外行（我是个会计TAT），我不知道这个辅助破解工具怎么用，只能先去研究了一下您曾经更新的这个 [修复晋江VIP章节方块问题](https://github.com/yingziwu/userscript/blob/291b591f50a547a89766e3de66fdc0d6f6ec7c78/scripts/MyNovelReader.user.js) ，发现6.4.3版本中，您更新的部分就是引用了一个“晋江文学城防盗字体对照表” 。

然后我就想，既然是晋江增加了新的防盗字体，那我自己再做一个新的对照表，替换到原来的 //@require 那里去，应该就可以了。

于是我切换到 gh-pages 分支，把 bundle.json 这个文件里面的内容，按照您那个字体对照表的格式，自己在greasyfork上[做了一个新的库](https://greasyfork.org/scripts/431741-%E6%99%8B%E6%B1%9F%E6%96%87%E5%AD%A6%E5%9F%8E%E9%98%B2%E7%9B%97%E5%AD%97%E4%BD%93%E5%AF%B9%E7%85%A7%E8%A1%A8-%E8%87%AA%E7%94%A8/code/%E6%99%8B%E6%B1%9F%E6%96%87%E5%AD%A6%E5%9F%8E%E9%98%B2%E7%9B%97%E5%AD%97%E4%BD%93%E5%AF%B9%E7%85%A7%E8%A1%A8-%E8%87%AA%E7%94%A8.js?version=966150)，然后替换了您的6.4.3版本的那个//@require，发现果然可以用了！所有的方块全都解决掉了！

但是就在今天，晋江的防盗字体似乎又更新了一次，我今天下午再次使用您刚刚更新过的 bundle.json 这个文件里的内容，按照上面操作重新制作了一下之后，发现在线阅读时，前一半VIP章节完全正常没有方框，后半VIP章节还是存在方框，不知道是哪里出了问题。（前面那个库的链接就是我9月1日刚刚做的。）

在这个问题下多次打扰，非常感谢大佬的帮助。因为是纯粹的外行人，我不知道自己的描述是否恰当，可能有些用词不当的地方还请您见谅！

**Comment by yingziwu** [comment]
本地字体数据更新频率跟不上晋江字体增加速度，这个问题我也遇到了。

解决方法很简单，那就是引入远程字体，当本地字体对照表数据未找到相关字体时，尝试向远程接口请求数据。

本项目 [server.py](https://github.com/yingziwu/jjwxcFontTables/blob/master/server.py) 便是一个HTTP服务器。

远程接口接收到客户端请求后，确认请求格式合法之后，先在本地字体数据缓存中查找被请求的字体数据，如未发现该字体。尝试从晋江文学城下载原始字体，然后启动解析服务对该字体进行解析（优化识别算法之后，一般可在5秒内完成识别）。最后将字体数据以响应形式返回客户端。

这样一来，远程客户端总能获得相应的字体数据，无论该字体是不是新字体。而本项目也可以借用客户端的请求发现晋江新增的防盗字体。然后定期将这些字体包含至git仓库，进行打包分发。

客户端的实现可以参考：[jjwxcFontDecode.ts](https://github.com/yingziwu/novel-downloader/blob/master/src/rules/lib/jjwxcFontDecode.ts)

**Comment by wumigg** [comment]
感谢回复！这个讲解太细致了，让我这个外行也能明白原理和思路，感谢您的耐心讲解！
根据我的理解，无论晋江在什么时候更新了多少个字体，[这个项目](https://github.com/yingziwu/jjwxcFontTables)都可以通过联网在线识别的方式，实现字体对照表的实时更新。
那么我还是需要运用这个工具，得到一份最新的字体对照表，再次写入到[小说阅读脚本](https://greasyfork.org/zh-CN/scripts/292-my-novel-reader)里才行。
现在我遇到的主要问题是不会使用这个工具。我的电脑上是安装了python环境的，但是打包下载之后main.py  patch.py  server.py这三个程序运行时都是一闪而过（只会这么描述，见笑了），之后tables文件夹里的内容也没有变动，这应该是程序运行并没有成功。
现在我能做的就是尽量去思考和摸索，避免做伸手党。除了我想到的这种方法之外，如果您有更好的方法来更新[小说阅读脚本](https://greasyfork.org/zh-CN/scripts/292-my-novel-reader)，也请您不吝赐教。
希望能再次得到您的帮助，十分感谢！
